title: Matt McClintock
description: Labs, writeups, and notes from my journey into cybersecurity.
theme: jekyll-theme-hacker


sass:
  style: compressed

plugins:
  - jekyll-sass-converter

# Tell Jekyll to include your custom CSS file
#include:
 # - assets/css/custom.css
  
collections:
  ctf:
    output: true
    permalink: /ctf/:title/
