title: Matt McClintock
description: My cybersecurity lab and writeup journal.
theme: jekyll-theme-hacker

#show_downloads: false

sass:
  style: compressed

plugins:
  - jekyll-sass-converter

# Tell Jekyll to include your custom CSS file
include:
  - assets/css/custom.css
  
collections:
  ctf:
    output: true
    permalink: /ctf/:title/
